[MeristPerkPack.X2DLCInfo_MeristPerkPack]

+WeaponTiers = (Tech = "alien",         Tier = 2)

+WeaponTiers = (Tech = "laser",         Tier = 1)

+WeaponTiers = (Tech = "coil",          Tier = 3)
+WeaponTiers = (Tech = "coil_lw",       Tier = 3)

+WeaponTiers = (Tech = "lw_magnetic",   Tier = 2)
+WeaponTiers = (Tech = "lw_coil",       Tier = 3)
+WeaponTiers = (Tech = "lw_beam",       Tier = 4)

[MeristPerkPack.X2AbilitySet_Merist]

+Blademaster_AdditionalAbilities = "MZSlingBlade"

+BombAndRun_AllowedAbilities = "Fire_UBGL_Conv"
+BombAndRun_AllowedAbilities = "Fire_UBGL_Mag"
+BombAndRun_AllowedAbilities = "Fire_UBGL_Beam"
+BombAndRun_AllowedAbilities = "IRI_ThrowMolotov"
+BombAndRun_AllowedAbilities = "IRI_ThrowPipeBomb"
+BombAndRun_AllowedAbilities = "IRI_Duke_ThrowPipeBomb"
+BombAndRun_AllowedAbilities = "ThrowProximityCLAYMORE"
+BombAndRun_AllowedAbilities = "ThrowSubSonicGrenade"
+BombAndRun_AllowedAbilities = "MusashiThrowFlashbang"
+BombAndRun_AllowedAbilities = "GrenadeThrow"
+BombAndRun_AllowedAbilities = "IRI_LaunchOrdnance"
+BombAndRun_AllowedAbilities = "IRI_BlastOrdnance"

; Primary only standard shots
+ColdBlooded_AllowedAbilities = "StandardShot"
+ColdBlooded_AllowedAbilities = "SniperStandardFire"

+ColdBlooded_AllowedAbilities = "AnimaGate"
+ColdBlooded_AllowedAbilities = "ShadowFireRS"
+ColdBlooded_AllowedAbilities = "ShadowFireNonSniperRS"
+ColdBlooded_AllowedAbilities = "StandardGhostShot"
+ColdBlooded_AllowedAbilities = "ShadowOps_ReadyForAnything"
+ColdBlooded_AllowedAbilities = "StabilizedShotM1"
+ColdBlooded_AllowedAbilities = "StabilizedShotM2"
+ColdBlooded_AllowedAbilities = "StabilizedShotM3"
+ColdBlooded_AllowedAbilities = "PenaltyShot"
+ColdBlooded_AllowedAbilities = "shivstandardshot"
+ColdBlooded_AllowedAbilities = "GlaiveShot"
+ColdBlooded_AllowedAbilities = "DualGlaiveShot"
+ColdBlooded_AllowedAbilities = "DPTT_MilitiaStandardShot"
+ColdBlooded_AllowedAbilities = "Exv_StandardShot"
+ColdBlooded_AllowedAbilities = "ISForcePushShot"
+ColdBlooded_AllowedAbilities = "ReaverShot"
+ColdBlooded_AllowedAbilities = "LWDroneShock"
+ColdBlooded_AllowedAbilities = "VCP_FireLightning"
+ColdBlooded_AllowedAbilities = "VCP_FirePush"

; Always non-turn-ending standard shots
+ColdBlooded_AllowedAbilities = "StandardShot_NoEnd"
+ColdBlooded_AllowedAbilities = "Blaster"
+ColdBlooded_AllowedAbilities = "BlasterDuringCannon"
+ColdBlooded_AllowedAbilities = "BulletSwarmRS"
+ColdBlooded_AllowedAbilities = "BulletSwarmRS2"
+ColdBlooded_AllowedAbilities = "LightEmUp"
+ColdBlooded_AllowedAbilities = "BD_LightEmUp_LW"
+ColdBlooded_AllowedAbilities = "RM_SniperStandardFire_NoEnd"
+ColdBlooded_AllowedAbilities = "PA_Blaster"
+ColdBlooded_AllowedAbilities = "PA_BlasterDuringCannon"
+ColdBlooded_AllowedAbilities = "CloudSweeperShot"
+ColdBlooded_AllowedAbilities = "BU_ATST_SingleActionShot"

; Action point refund standard shots
+ColdBlooded_AllowedAbilities = "ShadowOps_Reposition"
+ColdBlooded_AllowedAbilities = "RelocationShot"
+ColdBlooded_AllowedAbilities = "Spectrum_Reposition"
+ColdBlooded_AllowedAbilities = "StrafingShot"

; Snap Shots
+ColdBlooded_AllowedAbilities = "LW2WotC_SnapShot"
+ColdBlooded_AllowedAbilities = "SnapShotRS"
+ColdBlooded_AllowedAbilities = "EMG_SnapShot"
+ColdBlooded_AllowedAbilities = "ShadowOps_SnapShotShot"
+ColdBlooded_AllowedAbilities = "SnapShot"
+ColdBlooded_AllowedAbilities = "MZSnapRuneshot"
+ColdBlooded_AllowedAbilities = "SnapShotAL"
+ColdBlooded_AllowedAbilities = "ABBSnapShot"
+ColdBlooded_AllowedAbilities = "WOTC_APA_Snapshot"

; Snap Shot without penalty
+ColdBlooded_AllowedAbilities = "HunterRifleShot"
+ColdBlooded_AllowedAbilities = "Lucu_Sniper_SniperRifleShot"
+ColdBlooded_AllowedAbilities = "RTStandardSniperShot"

; Can hit multiple targets but are the standard shots for their respective guns or replace a standard shot
+ColdBlooded_AllowedAbilities = "ARFMTeslaTrooperShot"
+ColdBlooded_AllowedAbilities = "ARFMTalKhazanShotTargeted"
+ColdBlooded_AllowedAbilities = "AHWTalKhazanShotAlien"
+ColdBlooded_AllowedAbilities = "AHWCoringBeam"
+ColdBlooded_AllowedAbilities = "AHWHeavyMechtoidStandardShot"
+ColdBlooded_AllowedAbilities = "ARFMStandardShot_Explosive"

; Secondary standard shots (but can be primary with Primary Secondaries)
+ColdBlooded_AllowedAbilities = "PistolStandardShot"
+ColdBlooded_AllowedAbilities = "PM_Shot_All"
+ColdBlooded_AllowedAbilities = "WOTC_APA_Gunslinger_PistolShot"
+ColdBlooded_AllowedAbilities = "IRI_BH_FirePistol"
+ColdBlooded_AllowedAbilities = "IRI_Duke_FirePistol"
+ColdBlooded_AllowedAbilities = "PurifierPistolStandardShot"
+ColdBlooded_AllowedAbilities = "MrCPistolStandardShot"
+ColdBlooded_AllowedAbilities = "ISForcePushPistolShot"
+ColdBlooded_AllowedAbilities = "AHWBigIronShot"
+ColdBlooded_AllowedAbilities = "PistolStandardShot_MPP"
+ColdBlooded_AllowedAbilities = "VCP_FireShock"
+ColdBlooded_AllowedAbilities = "AutoFanFire_CV"
+ColdBlooded_AllowedAbilities = "AutoFanFire_MG"
+ColdBlooded_AllowedAbilities = "AutoFanFire_BM"
+ColdBlooded_AllowedAbilities = "AutoFanFire_Chosen"



; Primary only standard shots
+Relentless_AllowedAbilities = "StandardShot"
+Relentless_AllowedAbilities = "SniperStandardFire"

+Relentless_AllowedAbilities = "AnimaGate"
+Relentless_AllowedAbilities = "ShadowFireRS"
+Relentless_AllowedAbilities = "ShadowFireNonSniperRS"
+Relentless_AllowedAbilities = "StandardGhostShot"
+Relentless_AllowedAbilities = "ShadowOps_ReadyForAnything"
+Relentless_AllowedAbilities = "StabilizedShotM1"
+Relentless_AllowedAbilities = "StabilizedShotM2"
+Relentless_AllowedAbilities = "StabilizedShotM3"
+Relentless_AllowedAbilities = "PenaltyShot"
+Relentless_AllowedAbilities = "shivstandardshot"
+Relentless_AllowedAbilities = "GlaiveShot"
+Relentless_AllowedAbilities = "DualGlaiveShot"
+Relentless_AllowedAbilities = "DPTT_MilitiaStandardShot"
+Relentless_AllowedAbilities = "Exv_StandardShot"
+Relentless_AllowedAbilities = "ISForcePushShot"
+Relentless_AllowedAbilities = "ReaverShot"
+Relentless_AllowedAbilities = "LWDroneShock"
+Relentless_AllowedAbilities = "VCP_FireLightning"
+Relentless_AllowedAbilities = "VCP_FirePush"

; Always non-turn-ending standard shots
+Relentless_AllowedAbilities = "StandardShot_NoEnd"
+Relentless_AllowedAbilities = "Blaster"
+Relentless_AllowedAbilities = "BlasterDuringCannon"
+Relentless_AllowedAbilities = "BulletSwarmRS"
+Relentless_AllowedAbilities = "BulletSwarmRS2"
+Relentless_AllowedAbilities = "LightEmUp"
+Relentless_AllowedAbilities = "BD_LightEmUp_LW"
+Relentless_AllowedAbilities = "RM_SniperStandardFire_NoEnd"
+Relentless_AllowedAbilities = "PA_Blaster"
+Relentless_AllowedAbilities = "PA_BlasterDuringCannon"
+Relentless_AllowedAbilities = "CloudSweeperShot"
+Relentless_AllowedAbilities = "BU_ATST_SingleActionShot"

; Action point refund standard shots
+Relentless_AllowedAbilities = "ShadowOps_Reposition"
+Relentless_AllowedAbilities = "RelocationShot"
+Relentless_AllowedAbilities = "Spectrum_Reposition"
+Relentless_AllowedAbilities = "StrafingShot"

; Snap Shots
+Relentless_AllowedAbilities = "LW2WotC_SnapShot"
+Relentless_AllowedAbilities = "SnapShotRS"
+Relentless_AllowedAbilities = "EMG_SnapShot"
+Relentless_AllowedAbilities = "ShadowOps_SnapShotShot"
+Relentless_AllowedAbilities = "SnapShot"
+Relentless_AllowedAbilities = "MZSnapRuneshot"
+Relentless_AllowedAbilities = "SnapShotAL"
+Relentless_AllowedAbilities = "ABBSnapShot"
+Relentless_AllowedAbilities = "WOTC_APA_Snapshot"

; Snap Shot without penalty
+Relentless_AllowedAbilities = "HunterRifleShot"
+Relentless_AllowedAbilities = "Lucu_Sniper_SniperRifleShot"
+Relentless_AllowedAbilities = "RTStandardSniperShot"

; Can hit multiple targets but are the standard shots for their respective guns or replace a standard shot
+Relentless_AllowedAbilities = "ARFMTeslaTrooperShot"
+Relentless_AllowedAbilities = "ARFMTalKhazanShotTargeted"
+Relentless_AllowedAbilities = "AHWTalKhazanShotAlien"
+Relentless_AllowedAbilities = "AHWCoringBeam"
+Relentless_AllowedAbilities = "AHWHeavyMechtoidStandardShot"
+Relentless_AllowedAbilities = "ARFMStandardShot_Explosive"

; Secondary standard shots (but can be primary with Primary Secondaries)
+Relentless_AllowedAbilities = "PistolStandardShot"
+Relentless_AllowedAbilities = "PM_Shot_All"
+Relentless_AllowedAbilities = "WOTC_APA_Gunslinger_PistolShot"
+Relentless_AllowedAbilities = "IRI_BH_FirePistol"
+Relentless_AllowedAbilities = "IRI_Duke_FirePistol"
+Relentless_AllowedAbilities = "PurifierPistolStandardShot"
+Relentless_AllowedAbilities = "MrCPistolStandardShot"
+Relentless_AllowedAbilities = "ISForcePushPistolShot"
+Relentless_AllowedAbilities = "AHWBigIronShot"
+Relentless_AllowedAbilities = "PistolStandardShot_MPP"
+Relentless_AllowedAbilities = "VCP_FireShock"
+Relentless_AllowedAbilities = "AutoFanFire_CV"
+Relentless_AllowedAbilities = "AutoFanFire_MG"
+Relentless_AllowedAbilities = "AutoFanFire_BM"
+Relentless_AllowedAbilities = "AutoFanFire_Chosen"



; Primary only standard shots
+TraverseFire_AllowedAbilities = "StandardShot"
+TraverseFire_AllowedAbilities = "SniperStandardFire"

+TraverseFire_AllowedAbilities = "AnimaGate"
+TraverseFire_AllowedAbilities = "ShadowFireRS"
+TraverseFire_AllowedAbilities = "ShadowFireNonSniperRS"
+TraverseFire_AllowedAbilities = "StandardGhostShot"
+TraverseFire_AllowedAbilities = "ShadowOps_ReadyForAnything"
+TraverseFire_AllowedAbilities = "StabilizedShotM1"
+TraverseFire_AllowedAbilities = "StabilizedShotM2"
+TraverseFire_AllowedAbilities = "StabilizedShotM3"
+TraverseFire_AllowedAbilities = "PenaltyShot"
+TraverseFire_AllowedAbilities = "shivstandardshot"
+TraverseFire_AllowedAbilities = "GlaiveShot"
+TraverseFire_AllowedAbilities = "DualGlaiveShot"
+TraverseFire_AllowedAbilities = "DPTT_MilitiaStandardShot"
+TraverseFire_AllowedAbilities = "Exv_StandardShot"
+TraverseFire_AllowedAbilities = "ISForcePushShot"
+TraverseFire_AllowedAbilities = "ReaverShot"
+TraverseFire_AllowedAbilities = "LWDroneShock"
+TraverseFire_AllowedAbilities = "VCP_FireLightning"
+TraverseFire_AllowedAbilities = "VCP_FirePush"

; Always non-turn-ending standard shots
+TraverseFire_AllowedAbilities = "StandardShot_NoEnd"
+TraverseFire_AllowedAbilities = "Blaster"
+TraverseFire_AllowedAbilities = "BlasterDuringCannon"
+TraverseFire_AllowedAbilities = "BulletSwarmRS"
+TraverseFire_AllowedAbilities = "BulletSwarmRS2"
+TraverseFire_AllowedAbilities = "LightEmUp"
+TraverseFire_AllowedAbilities = "BD_LightEmUp_LW"
+TraverseFire_AllowedAbilities = "RM_SniperStandardFire_NoEnd"
+TraverseFire_AllowedAbilities = "PA_Blaster"
+TraverseFire_AllowedAbilities = "PA_BlasterDuringCannon"
+TraverseFire_AllowedAbilities = "CloudSweeperShot"
+TraverseFire_AllowedAbilities = "BU_ATST_SingleActionShot"

; Action point refund standard shots
+TraverseFire_AllowedAbilities = "ShadowOps_Reposition"
+TraverseFire_AllowedAbilities = "RelocationShot"
+TraverseFire_AllowedAbilities = "Spectrum_Reposition"
+TraverseFire_AllowedAbilities = "StrafingShot"

; Snap Shots
+TraverseFire_AllowedAbilities = "LW2WotC_SnapShot"
+TraverseFire_AllowedAbilities = "SnapShotRS"
+TraverseFire_AllowedAbilities = "EMG_SnapShot"
+TraverseFire_AllowedAbilities = "ShadowOps_SnapShotShot"
+TraverseFire_AllowedAbilities = "SnapShot"
+TraverseFire_AllowedAbilities = "MZSnapRuneshot"
+TraverseFire_AllowedAbilities = "SnapShotAL"
+TraverseFire_AllowedAbilities = "ABBSnapShot"
+TraverseFire_AllowedAbilities = "WOTC_APA_Snapshot"

; Snap Shot without penalty
+TraverseFire_AllowedAbilities = "HunterRifleShot"
+TraverseFire_AllowedAbilities = "Lucu_Sniper_SniperRifleShot"
+TraverseFire_AllowedAbilities = "RTStandardSniperShot"

; Can hit multiple targets but are the standard shots for their respective guns or replace a standard shot
+TraverseFire_AllowedAbilities = "ARFMTeslaTrooperShot"
+TraverseFire_AllowedAbilities = "ARFMTalKhazanShotTargeted"
+TraverseFire_AllowedAbilities = "AHWTalKhazanShotAlien"
+TraverseFire_AllowedAbilities = "AHWCoringBeam"
+TraverseFire_AllowedAbilities = "AHWHeavyMechtoidStandardShot"
+TraverseFire_AllowedAbilities = "ARFMStandardShot_Explosive"

; Secondary standard shots (but can be primary with Primary Secondaries)
+TraverseFire_AllowedAbilities = "PistolStandardShot"
+TraverseFire_AllowedAbilities = "PM_Shot_All"
+TraverseFire_AllowedAbilities = "WOTC_APA_Gunslinger_PistolShot"
+TraverseFire_AllowedAbilities = "IRI_BH_FirePistol"
+TraverseFire_AllowedAbilities = "IRI_Duke_FirePistol"
+TraverseFire_AllowedAbilities = "PurifierPistolStandardShot"
+TraverseFire_AllowedAbilities = "MrCPistolStandardShot"
+TraverseFire_AllowedAbilities = "ISForcePushPistolShot"
+TraverseFire_AllowedAbilities = "AHWBigIronShot"
+TraverseFire_AllowedAbilities = "PistolStandardShot_MPP"
+TraverseFire_AllowedAbilities = "VCP_FireShock"
+TraverseFire_AllowedAbilities = "AutoFanFire_CV"
+TraverseFire_AllowedAbilities = "AutoFanFire_MG"
+TraverseFire_AllowedAbilities = "AutoFanFire_BM"
+TraverseFire_AllowedAbilities = "AutoFanFire_Chosen"




; Primary only standard shots
+TroubleShooter_AllowedAbilities = "StandardShot"
+TroubleShooter_AllowedAbilities = "SniperStandardFire"

+TroubleShooter_AllowedAbilities = "AnimaGate"
+TroubleShooter_AllowedAbilities = "ShadowFireRS"
+TroubleShooter_AllowedAbilities = "ShadowFireNonSniperRS"
+TroubleShooter_AllowedAbilities = "StandardGhostShot"
+TroubleShooter_AllowedAbilities = "ShadowOps_ReadyForAnything"
+TroubleShooter_AllowedAbilities = "StabilizedShotM1"
+TroubleShooter_AllowedAbilities = "StabilizedShotM2"
+TroubleShooter_AllowedAbilities = "StabilizedShotM3"
+TroubleShooter_AllowedAbilities = "PenaltyShot"
+TroubleShooter_AllowedAbilities = "shivstandardshot"
+TroubleShooter_AllowedAbilities = "GlaiveShot"
+TroubleShooter_AllowedAbilities = "DualGlaiveShot"
+TroubleShooter_AllowedAbilities = "DPTT_MilitiaStandardShot"
+TroubleShooter_AllowedAbilities = "Exv_StandardShot"
+TroubleShooter_AllowedAbilities = "ISForcePushShot"
+TroubleShooter_AllowedAbilities = "ReaverShot"
+TroubleShooter_AllowedAbilities = "LWDroneShock"
+TroubleShooter_AllowedAbilities = "VCP_FireLightning"
+TroubleShooter_AllowedAbilities = "VCP_FirePush"

; Always non-turn-ending standard shots
+TroubleShooter_AllowedAbilities = "StandardShot_NoEnd"
+TroubleShooter_AllowedAbilities = "Blaster"
+TroubleShooter_AllowedAbilities = "BlasterDuringCannon"
+TroubleShooter_AllowedAbilities = "BulletSwarmRS"
+TroubleShooter_AllowedAbilities = "BulletSwarmRS2"
+TroubleShooter_AllowedAbilities = "LightEmUp"
+TroubleShooter_AllowedAbilities = "BD_LightEmUp_LW"
+TroubleShooter_AllowedAbilities = "RM_SniperStandardFire_NoEnd"
+TroubleShooter_AllowedAbilities = "PA_Blaster"
+TroubleShooter_AllowedAbilities = "PA_BlasterDuringCannon"
+TroubleShooter_AllowedAbilities = "CloudSweeperShot"
+TroubleShooter_AllowedAbilities = "BU_ATST_SingleActionShot"

; Action point refund standard shots
+TroubleShooter_AllowedAbilities = "ShadowOps_Reposition"
+TroubleShooter_AllowedAbilities = "RelocationShot"
+TroubleShooter_AllowedAbilities = "Spectrum_Reposition"
+TroubleShooter_AllowedAbilities = "StrafingShot"

; Snap Shots
+TroubleShooter_AllowedAbilities = "LW2WotC_SnapShot"
+TroubleShooter_AllowedAbilities = "SnapShotRS"
+TroubleShooter_AllowedAbilities = "EMG_SnapShot"
+TroubleShooter_AllowedAbilities = "ShadowOps_SnapShotShot"
+TroubleShooter_AllowedAbilities = "SnapShot"
+TroubleShooter_AllowedAbilities = "MZSnapRuneshot"
+TroubleShooter_AllowedAbilities = "SnapShotAL"
+TroubleShooter_AllowedAbilities = "ABBSnapShot"
+TroubleShooter_AllowedAbilities = "WOTC_APA_Snapshot"

; Snap Shot without penalty
+TroubleShooter_AllowedAbilities = "HunterRifleShot"
+TroubleShooter_AllowedAbilities = "Lucu_Sniper_SniperRifleShot"
+TroubleShooter_AllowedAbilities = "RTStandardSniperShot"

; Can hit multiple targets but are the standard shots for their respective guns or replace a standard shot
+TroubleShooter_AllowedAbilities = "ARFMTeslaTrooperShot"
+TroubleShooter_AllowedAbilities = "ARFMTalKhazanShotTargeted"
+TroubleShooter_AllowedAbilities = "AHWTalKhazanShotAlien"
+TroubleShooter_AllowedAbilities = "AHWCoringBeam"
+TroubleShooter_AllowedAbilities = "AHWHeavyMechtoidStandardShot"
+TroubleShooter_AllowedAbilities = "ARFMStandardShot_Explosive"

; Secondary standard shots (but can be primary with Primary Secondaries)
+TroubleShooter_AllowedAbilities = "PistolStandardShot"
+TroubleShooter_AllowedAbilities = "PM_Shot_All"
+TroubleShooter_AllowedAbilities = "WOTC_APA_Gunslinger_PistolShot"
+TroubleShooter_AllowedAbilities = "IRI_BH_FirePistol"
+TroubleShooter_AllowedAbilities = "IRI_Duke_FirePistol"
+TroubleShooter_AllowedAbilities = "PurifierPistolStandardShot"
+TroubleShooter_AllowedAbilities = "MrCPistolStandardShot"
+TroubleShooter_AllowedAbilities = "ISForcePushPistolShot"
+TroubleShooter_AllowedAbilities = "AHWBigIronShot"
+TroubleShooter_AllowedAbilities = "PistolStandardShot_MPP"
+TroubleShooter_AllowedAbilities = "VCP_FireShock"
+TroubleShooter_AllowedAbilities = "AutoFanFire_CV"
+TroubleShooter_AllowedAbilities = "AutoFanFire_MG"
+TroubleShooter_AllowedAbilities = "AutoFanFire_BM"
+TroubleShooter_AllowedAbilities = "AutoFanFire_Chosen"