[XComGame.X2AIBTBehaviorTree]
;   Copied from Iridar's Gene Mods
;   --> Copied from K's Officer Class
+Behaviors=(BehaviorName=M31_SidewinderMove, NodeType=Selector, Child[0]=FallBack, Child[1]=HighCoverFallback, Child[2]=FallBackUnsafe, Child[3]=DoCower, Child[4]=SkipMove)
