[MeristOrdnanceSlot.OrdnanceInventorySlot]
;   This is the Inventory Slot that will be used by Ordnance slots.
;   DO NOT change this if you don't know what you're doing.
; UseSlot = eInvSlot_ExtraGrenadePocket
UseSlot = eInvSlot_Unknown

bAlwaysAllowsGrenades = true
bAlwaysAllowsRockets = true
bAlwaysAllowsAmmo = true

; +AbilityUnlocksSlot = (AbilityName = "", NumSlots = 0)
; +AbilityAllowsGrenadesInSlot = ""
; +AbilityAllowsRocketsInSlot = ""
; +AbilityAllowsAmmoInSlot = ""

+AbilityUnlocksSlot = (AbilityName = "M31_SK_FullKit", NumSlots = "3")