[MeristOrdnanceSlot.OrdnanceInventorySlot]
;   This is the Inventory Slot that will be used by Ordnance slots.
;   DO NOT change this if you don't know what you're doing.
; UseSlot = eInvSlot_OrdnancePocket
UseSlot = eInvSlot_ExtraGrenadePocket
; UseSlot = eInvSlot_Unknown

bAlwaysAllowsGrenades = false
bAlwaysAllowsRockets = false
bAlwaysAllowsAmmo = false

; +AbilityUnlocksSlot = (AbilityName = "", NumSlots = 0)
; +AbilityAllowsGrenadesInSlot = ""
; +AbilityAllowsRocketsInSlot = ""
; +AbilityAllowsAmmoInSlot = ""

+AbilityUnlocksSlot = (AbilityName = "M31_SK_DeepPockets", NumSlots = 3)
+AbilityAllowsGrenadesInSlot = "M31_SK_DeepPockets"
+AbilityAllowsAmmoInSlot = "M31_SK_DeepPockets"