[XComGame.X2AbilityTemplateManager]
+AbilityUnlocksGrenadePocket = "M31_SuperheavyOrdnance"
+AbilityUnlocksGrenadePocket = "M31_PA_WS_WinterSoldier"
+AbilityUnlocksGrenadePocket = "M31_ShockGrenadier"
+AbilityUnlocksGrenadePocket = "M31_SmokeGrenadier"

+EffectUpdatesOnMove = "M31_ShadowPhase"

[XComGame.X2PerkPackages]
+PerkPackage = M31_Perks_Vipers
+PerkPackage = M31_Perks_HoloTargeting
+PerkPackage = M31_Perks_Psi
+PerkPackage = M31_Perks_SK

[XComGame.X2ItemTemplateManager]
+Loadouts = (LoadoutName="M31_SpectralZombie_M1_Loadout", Items[0]=(Item="M31_SpectralZombie_M1_Melee"))
+Loadouts = (LoadoutName="M31_SpectralZombie_M2_Loadout", Items[0]=(Item="M31_SpectralZombie_M2_Melee"))
+Loadouts = (LoadoutName="M31_SpectralZombie_M3_Loadout", Items[0]=(Item="M31_SpectralZombie_M3_Melee"))

+Loadouts = (LoadoutName="M31_AdvSpectralZombie_M1_Loadout", Items[0]=(Item="M31_AdvSpectralZombie_M1_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralZombie_M2_Loadout", Items[0]=(Item="M31_AdvSpectralZombie_M2_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralZombie_M3_Loadout", Items[0]=(Item="M31_AdvSpectralZombie_M3_Melee"))

+Loadouts = (LoadoutName="M31_SpectralLancer_M1_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_SpectralLancer_M1_Melee"))
+Loadouts = (LoadoutName="M31_SpectralLancer_M2_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_SpectralLancer_M2_Melee"))
+Loadouts = (LoadoutName="M31_SpectralLancer_M3_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_SpectralLancer_M3_Melee"))

+Loadouts = (LoadoutName="M31_AdvSpectralLancer_M1_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_AdvSpectralLancer_M1_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralLancer_M2_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_AdvSpectralLancer_M2_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralLancer_M3_Loadout", Items[0]=(Item="M31_SpectralLancer_FakeRifle"), Items[1]=(Item="M31_AdvSpectralLancer_M3_Melee"))

+Loadouts = (LoadoutName="M31_SpectralCreature_M1_Loadout", Items[0]=(Item="M31_SpectralCreature_M1_Melee"))
+Loadouts = (LoadoutName="M31_SpectralCreature_M2_Loadout", Items[0]=(Item="M31_SpectralCreature_M2_Melee"))
+Loadouts = (LoadoutName="M31_SpectralCreature_M3_Loadout", Items[0]=(Item="M31_SpectralCreature_M3_Melee"))

+Loadouts = (LoadoutName="M31_AdvSpectralCreature_M1_Loadout", Items[0]=(Item="M31_AdvSpectralCreature_M1_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralCreature_M2_Loadout", Items[0]=(Item="M31_AdvSpectralCreature_M2_Melee"))
+Loadouts = (LoadoutName="M31_AdvSpectralCreature_M3_Loadout", Items[0]=(Item="M31_AdvSpectralCreature_M3_Melee"))

[MeristPerkPack.X2Action_Fire_Fork_Volt]
ParticleSystemName = "FX_Templar_Volt.P_Volt_Tether"
StartingSocket = R_Hand
TargetSocket = FX_CHEST
ChainDelay = 0.25
bUseCustomFireAnim = true
bUseCustomSelfFireAnim = false
AnimName = "HL_Volt"

[MeristPerkPack.X2Action_Fire_ChainingJolt]
; ParticleSystemName = "FX_MZChainJolt.P_ChainJolt_Tether"
ParticleSystemName = "M31_CS_FX_Operator.ChainingJolt.P_Operator_ChainingJolt"
StartingSocket = FX_Probe
TargetSocket = FX_CHEST
ChainDelay = 0.25
bUseCustomFireAnim = false
bUseCustomSelfFireAnim = true

[MeristPerkPack.X2Action_Fire_ArcMindspin]
ParticleSystemName = "FX_MindScorch.P_MindScorch_Tether"
StartingSocket = FX_Head
TargetSocket = FX_Head
ChainDelay = 0.95
bUseCustomFireAnim = true

[MeristPerkPack.X2Action_MeristPinionsAttack]
; Delay in seconds for each next projectile after the first
MinProjectileTimeDelaySec = 0.10
MaxProjectileTimeDelaySec = 0.30

[MeristPerkPack.X2TargetingMethod_MeristPinions]
TextFieldOffsetX = 60
TextFieldOffsetY = -60