; This adds bitterfrost to the Frost Legion aliens' primary weapons.
[MZFrostRounds.BitterfrostHelper]

+AddBitterfrostEffectToWeapons = "M31_SpectralZombie_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralZombie_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralZombie_M3_Melee"

+AddBitterfrostEffectToWeapons = "M31_AdvSpectralZombie_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralZombie_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralZombie_M3_Melee"

+AddBitterfrostEffectToWeapons = "M31_SpectralLancer_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralLancer_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralLancer_M3_Melee"

+AddBitterfrostEffectToWeapons = "M31_AdvSpectralLancer_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralLancer_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralLancer_M3_Melee"

+AddBitterfrostEffectToWeapons = "M31_SpectralCreature_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralCreature_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_SpectralCreature_M3_Melee"

+AddBitterfrostEffectToWeapons = "M31_AdvSpectralCreature_M1_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralCreature_M2_Melee"
+AddBitterfrostEffectToWeapons = "M31_AdvSpectralCreature_M3_Melee"