[MeristEnhancedShieldEffects.X2DLCInfo_MeristEnhancedShieldEffects]
DLCIdentifier = "MeristEnhancedShieldEffects"
bLog = false

[MeristBuffMe.X2DownloadableContentInfo_MeristBuffMe]
DLCIdentifier = "MeristBuffMe"
bLog = false

[MeristPerkPack CHModDependency]
DisplayName = "MeristPerkPack"

[MeristPerkPack CHDLCRunOrder]
RunPriorityGroup = RUN_LAST
+RunAfter = "WOTC_ExtendedGrenadeTweaks"

[MeristPerkPack2 CHModDependency]
DisplayName = "MeristPerkPack2"

[MeristPerkPack2 CHDLCRunOrder]
RunPriorityGroup = RUN_LAST

[XComGame.CHHelpers]
+AbilityTemplatePerksToLoad = M31_ZoneOfControl_Passive
; Playable Aliens
+AbilityTemplatePerksToLoad = M31_PA_FrostSpit
+AbilityTemplatePerksToLoad = M31_PA_FrostBreath
; Psionics
+AbilityTemplatePerksToLoad = M31_ShadowPhase
; SK
+AbilityTemplatePerksToLoad = M31_SK_Pinions_Attack
; For Holotargeting
+AbilityTemplatePerksToLoad = M31_AssaultShot
+AbilityTemplatePerksToLoad = M31_DeathAdder
+AbilityTemplatePerksToLoad = M31_DisarmingShot
+AbilityTemplatePerksToLoad = M31_DisarmingShot_SnapShot
+AbilityTemplatePerksToLoad = M31_Maim
+AbilityTemplatePerksToLoad = M31_Maim_SnapShot
+AbilityTemplatePerksToLoad = M31_NeurotoxicShot
+AbilityTemplatePerksToLoad = M31_Pinpoint
+AbilityTemplatePerksToLoad = M31_SniperOverwatch_Attack
+AbilityTemplatePerksToLoad = M31_Sparkfire
+AbilityTemplatePerksToLoad = M31_SuppressingFire
+AbilityTemplatePerksToLoad = M31_WatchfulEye_Attack

[XComGame.CHHelpers]
+ValidReserveAPForUnitFlag = "M31_SniperOverwatch"
+ValidReserveAPForUnitFlag = "M31_PA_WS_LeadTheTargetActionPoint"

[MeristPerkPack.X2EventListener_GlobalListeners]
bLog = true
EventPriority_OnPostMissionUpdateSoldierHealing = 80

[MeristPerkPack.XCGS_Effect_PersistentAura]
bLog = true